services:
  jekyll:
    image: ghcr.io/fedemengo/al-folio:1.0.0
    command: bash -c "
      rm -f Gemfile.lock &&
      bundler exec jekyll serve --watch --port=8080 --host=0.0.0.0 --incremental --livereload"
    ports:
      - 8080:8080

    develop:
      watch:
        - action: sync
          path: .
          target: /srv/jekyll
          ignore:
            - node_modules/
            - _site/

